
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 15 11:38:55 CET 2014
//----------------------------------------------------

package name.martingeisse.phunky.runtime.parser;

/** CUP generated class containing symbol constants. */
@SuppressWarnings("all")
public class Tokens {
  /* terminals */
  public static final int BITWISE_XOR = 48;
  public static final int IDENTIFIER = 79;
  public static final int TIMES = 39;
  public static final int MOD_ASSIGN = 66;
  public static final int PARENT = 74;
  public static final int UNTIL = 25;
  public static final int BITWISE_OR = 47;
  public static final int LOCAL_VARIABLE = 80;
  public static final int CATCH = 35;
  public static final int COMMA = 13;
  public static final int THROW = 33;
  public static final int TIMES_ASSIGN = 64;
  public static final int INCREMENT = 60;
  public static final int PROTECTED = 18;
  public static final int INTEGER_LITERAL = 77;
  public static final int SELF = 73;
  public static final int ARRAY = 72;
  public static final int ELSEIF = 30;
  public static final int OPENING_CURLY_BRACE = 4;
  public static final int FINAL = 21;
  public static final int BITWISE_NOT = 45;
  public static final int CLOSING_CURLY_BRACE = 5;
  public static final int BITWISE_OR_ASSIGN = 68;
  public static final int BOOLEAN_LITERAL = 76;
  public static final int NOT_IDENTICAL = 54;
  public static final int MOD = 41;
  public static final int SHIFT_LEFT = 49;
  public static final int CLASS = 15;
  public static final int ABSTRACT = 20;
  public static final int SHIFT_LEFT_ASSIGN = 70;
  public static final int SCOPE_RESOLUTION = 10;
  public static final int PLUS = 37;
  public static final int DIVIDE = 40;
  public static final int WHILE = 27;
  public static final int EQUAL = 51;
  public static final int ASSIGN = 59;
  public static final int INTERFACE = 16;
  public static final int OPENING_SQUARE_BRACKET = 6;
  public static final int DO = 26;
  public static final int FOR = 23;
  public static final int MINUS_ASSIGN = 63;
  public static final int GREATER = 55;
  public static final int PUBLIC = 17;
  public static final int RETURN = 32;
  public static final int ELSE = 31;
  public static final int SHORTCUT_OR = 44;
  public static final int TRY = 34;
  public static final int BREAK = 28;
  public static final int SHORTCUT_AND = 43;
  public static final int NULL_LITERAL = 75;
  public static final int STRING_LITERAL = 78;
  public static final int EOF = 0;
  public static final int SEMICOLON = 9;
  public static final int SHIFT_RIGHT = 50;
  public static final int DECREMENT = 61;
  public static final int FUNCTION = 14;
  public static final int DIVIDE_ASSIGN = 65;
  public static final int MINUS = 38;
  public static final int OPENING_PARENTHESIS = 2;
  public static final int BITWISE_AND_ASSIGN = 67;
  public static final int RIGHT_ARROW = 8;
  public static final int CLOSING_SQUARE_BRACKET = 7;
  public static final int error = 1;
  public static final int LOGICAL_NOT = 42;
  public static final int NOT_EQUAL = 52;
  public static final int FINALLY = 36;
  public static final int IF = 29;
  public static final int GREATER_EQUAL = 57;
  public static final int PLUS_ASSIGN = 62;
  public static final int COLON = 12;
  public static final int IDENTICAL = 53;
  public static final int LESS_EQUAL = 58;
  public static final int FOREACH = 24;
  public static final int CLOSING_PARENTHESIS = 3;
  public static final int QUESTION_MARK = 11;
  public static final int LESS = 56;
  public static final int BITWISE_XOR_ASSIGN = 69;
  public static final int PRIVATE = 19;
  public static final int STATIC = 22;
  public static final int SHIFT_RIGHT_ASSIGN = 71;
  public static final int BITWISE_AND = 46;
}

