
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 29 22:15:28 CEST 2014
//----------------------------------------------------

package name.martingeisse.phunky.runtime.parser;

/** CUP generated class containing symbol constants. */
@SuppressWarnings("all")
public class Tokens {
  /* terminals */
  public static final int BITWISE_XOR = 49;
  public static final int IDENTIFIER = 80;
  public static final int TIMES = 40;
  public static final int MOD_ASSIGN = 67;
  public static final int PARENT = 75;
  public static final int VERBATIM_CONTENT = 2;
  public static final int UNTIL = 26;
  public static final int BITWISE_OR = 48;
  public static final int LOCAL_VARIABLE = 81;
  public static final int CATCH = 36;
  public static final int COMMA = 14;
  public static final int THROW = 34;
  public static final int TIMES_ASSIGN = 65;
  public static final int INCREMENT = 61;
  public static final int PROTECTED = 19;
  public static final int INTEGER_LITERAL = 78;
  public static final int SELF = 74;
  public static final int ARRAY = 73;
  public static final int ELSEIF = 31;
  public static final int OPENING_CURLY_BRACE = 5;
  public static final int FINAL = 22;
  public static final int BITWISE_NOT = 46;
  public static final int CLOSING_CURLY_BRACE = 6;
  public static final int BITWISE_OR_ASSIGN = 69;
  public static final int BOOLEAN_LITERAL = 77;
  public static final int NOT_IDENTICAL = 55;
  public static final int MOD = 42;
  public static final int SHIFT_LEFT = 50;
  public static final int CLASS = 16;
  public static final int ABSTRACT = 21;
  public static final int SHIFT_LEFT_ASSIGN = 71;
  public static final int SCOPE_RESOLUTION = 11;
  public static final int PLUS = 38;
  public static final int DIVIDE = 41;
  public static final int WHILE = 28;
  public static final int EQUAL = 52;
  public static final int ASSIGN = 60;
  public static final int INTERFACE = 17;
  public static final int OPENING_SQUARE_BRACKET = 7;
  public static final int DO = 27;
  public static final int FOR = 24;
  public static final int MINUS_ASSIGN = 64;
  public static final int GREATER = 56;
  public static final int PUBLIC = 18;
  public static final int RETURN = 33;
  public static final int ELSE = 32;
  public static final int SHORTCUT_OR = 45;
  public static final int TRY = 35;
  public static final int BREAK = 29;
  public static final int SHORTCUT_AND = 44;
  public static final int NULL_LITERAL = 76;
  public static final int STRING_LITERAL = 79;
  public static final int EOF = 0;
  public static final int SEMICOLON = 10;
  public static final int SHIFT_RIGHT = 51;
  public static final int DECREMENT = 62;
  public static final int FUNCTION = 15;
  public static final int DIVIDE_ASSIGN = 66;
  public static final int MINUS = 39;
  public static final int OPENING_PARENTHESIS = 3;
  public static final int BITWISE_AND_ASSIGN = 68;
  public static final int RIGHT_ARROW = 9;
  public static final int CLOSING_SQUARE_BRACKET = 8;
  public static final int error = 1;
  public static final int LOGICAL_NOT = 43;
  public static final int NOT_EQUAL = 53;
  public static final int FINALLY = 37;
  public static final int IF = 30;
  public static final int GREATER_EQUAL = 58;
  public static final int PLUS_ASSIGN = 63;
  public static final int COLON = 13;
  public static final int IDENTICAL = 54;
  public static final int LESS_EQUAL = 59;
  public static final int FOREACH = 25;
  public static final int CLOSING_PARENTHESIS = 4;
  public static final int QUESTION_MARK = 12;
  public static final int LESS = 57;
  public static final int BITWISE_XOR_ASSIGN = 70;
  public static final int PRIVATE = 20;
  public static final int STATIC = 23;
  public static final int SHIFT_RIGHT_ASSIGN = 72;
  public static final int BITWISE_AND = 47;
}

