//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Jun 11 22:12:34 CEST 2014
//----------------------------------------------------

package name.martingeisse.phunky.runtime.parser;

/** CUP generated class containing symbol constants. */
@SuppressWarnings("all")
public class Tokens {
	/* terminals */
	public static final int BITWISE_XOR = 55;

	public static final int IDENTIFIER = 86;

	public static final int TIMES = 46;

	public static final int MOD_ASSIGN = 73;

	public static final int IMPLEMENTS = 19;

	public static final int PARENT = 81;

	public static final int CONST = 27;

	public static final int VERBATIM_CONTENT = 2;

	public static final int UNTIL = 30;

	public static final int BITWISE_OR = 54;

	public static final int LOCAL_VARIABLE = 87;

	public static final int CATCH = 40;

	public static final int COMMA = 14;

	public static final int THROW = 38;

	public static final int TIMES_ASSIGN = 71;

	public static final int INCREMENT = 67;

	public static final int PROTECTED = 21;

	public static final int INTEGER_LITERAL = 84;

	public static final int SELF = 80;

	public static final int ARRAY = 79;

	public static final int ELSEIF = 35;

	public static final int OPENING_CURLY_BRACE = 5;

	public static final int VAR = 26;

	public static final int FINAL = 25;

	public static final int BITWISE_NOT = 52;

	public static final int CLOSING_CURLY_BRACE = 6;

	public static final int BITWISE_OR_ASSIGN = 75;

	public static final int BOOLEAN_LITERAL = 83;

	public static final int NOT_IDENTICAL = 61;

	public static final int MOD = 48;

	public static final int SHIFT_LEFT = 56;

	public static final int CLASS = 16;

	public static final int ABSTRACT = 24;

	public static final int SHIFT_LEFT_ASSIGN = 77;

	public static final int SCOPE_RESOLUTION = 11;

	public static final int PLUS = 44;

	public static final int DIVIDE = 47;

	public static final int WHILE = 32;

	public static final int EQUAL = 58;

	public static final int EXTENDS = 18;

	public static final int ASSIGN = 66;

	public static final int INTERFACE = 17;

	public static final int OPENING_SQUARE_BRACKET = 7;

	public static final int DO = 31;

	public static final int FOR = 28;

	public static final int MINUS_ASSIGN = 70;

	public static final int GREATER = 62;

	public static final int PUBLIC = 20;

	public static final int RETURN = 37;

	public static final int ELSE = 36;

	public static final int SHORTCUT_OR = 51;

	public static final int TRY = 39;

	public static final int BREAK = 33;

	public static final int ECHO = 43;

	public static final int SHORTCUT_AND = 50;

	public static final int NULL_LITERAL = 82;

	public static final int STRING_LITERAL = 85;

	public static final int EOF = 0;

	public static final int SEMICOLON = 10;

	public static final int SHIFT_RIGHT = 57;

	public static final int DECREMENT = 68;

	public static final int FUNCTION = 15;

	public static final int DIVIDE_ASSIGN = 72;

	public static final int MINUS = 45;

	public static final int OPENING_PARENTHESIS = 3;

	public static final int BITWISE_AND_ASSIGN = 74;

	public static final int RIGHT_ARROW = 9;

	public static final int CLOSING_SQUARE_BRACKET = 8;

	public static final int error = 1;

	public static final int LOGICAL_NOT = 49;

	public static final int NOT_EQUAL = 59;

	public static final int FINALLY = 41;

	public static final int IF = 34;

	public static final int GREATER_EQUAL = 64;

	public static final int PLUS_ASSIGN = 69;

	public static final int COLON = 13;

	public static final int IDENTICAL = 60;

	public static final int LESS_EQUAL = 65;

	public static final int FOREACH = 29;

	public static final int GLOBAL = 42;

	public static final int CLOSING_PARENTHESIS = 4;

	public static final int QUESTION_MARK = 12;

	public static final int LESS = 63;

	public static final int BITWISE_XOR_ASSIGN = 76;

	public static final int PRIVATE = 22;

	public static final int STATIC = 23;

	public static final int SHIFT_RIGHT_ASSIGN = 78;

	public static final int BITWISE_AND = 53;
}
